"""auto update

Revision ID: 2f3e9f3a7ba8
Revises: f62b612d5ace
Create Date: 2026-08-02 11:30:42.593011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f3e9f3a7ba8'
down_revision: Union[str, Sequence[str], None] = 'f62b612d5ace'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registrations', sa.Column('membership_status', sa.String(), nullable=True))
    op.add_column('registrations', sa.Column('approved_at', sa.String(), nullable=True))
    op.alter_column('registrations', 'notes',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('registrations', 'status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('registrations', 'membership_number',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('registrations', 'whatsapp_registration_sent',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('registrations', 'whatsapp_approval_sent',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('registrations', 'whatsapp_last_attempt',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('registrations', 'whatsapp_status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=True)
    op.drop_index(op.f('ix_registrations_user_id'), table_name='registrations')
    op.drop_column('registrations', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registrations', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_registrations_user_id'), 'registrations', ['user_id'], unique=False)
    op.alter_column('registrations', 'whatsapp_status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'none'::character varying"),
               existing_nullable=True)
    op.alter_column('registrations', 'whatsapp_last_attempt',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("''::character varying"),
               existing_nullable=True)
    op.alter_column('registrations', 'whatsapp_approval_sent',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('registrations', 'whatsapp_registration_sent',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('registrations', 'membership_number',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("''::character varying"),
               existing_nullable=True)
    op.alter_column('registrations', 'status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=False)
    op.alter_column('registrations', 'notes',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("''::character varying"),
               existing_nullable=True)
    op.drop_column('registrations', 'approved_at')
    op.drop_column('registrations', 'membership_status')
    # ### end Alembic commands ###