"""auto update

Revision ID: f62b612d5ace
Revises: 36fda216618a
Create Date: 2026-08-02 10:24:03.443155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f62b612d5ace'
down_revision: Union[str, Sequence[str], None] = '36fda216618a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registrations', sa.Column('business_type', sa.String(), nullable=False))
    op.add_column('registrations', sa.Column('membership_number', sa.String(), server_default='', nullable=True))
    op.add_column('registrations', sa.Column('whatsapp_registration_sent', sa.Boolean(), server_default='false', nullable=True))
    op.add_column('registrations', sa.Column('whatsapp_approval_sent', sa.Boolean(), server_default='false', nullable=True))
    op.add_column('registrations', sa.Column('whatsapp_last_attempt', sa.String(), server_default='', nullable=True))
    op.add_column('registrations', sa.Column('whatsapp_status', sa.String(), server_default='none', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registrations', 'whatsapp_status')
    op.drop_column('registrations', 'whatsapp_last_attempt')
    op.drop_column('registrations', 'whatsapp_approval_sent')
    op.drop_column('registrations', 'whatsapp_registration_sent')
    op.drop_column('registrations', 'membership_number')
    op.drop_column('registrations', 'business_type')
    # ### end Alembic commands ###