import { useEffect, useState } from 'react';
import { Download, Edit3, Eye, FileSpreadsheet, Plus, Printer, ReceiptText, RotateCcw, Trash2, Wallet } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Checkbox } from '@/components/ui/checkbox';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Progress } from '@/components/ui/progress';
import { Textarea } from '@/components/ui/textarea';
import { financialErpApi } from '@/lib/financialErpApi';
import { useBrand } from '@/lib/brand';
import type { Company, Expense, Revenue, ServiceType } from '@/types/financialErp';
import { CompactTable, Empty, FileButton, FormDialog, PageTitle, SafeDateInput, StatusBadge, money } from './FinancialUi';

type Props={companies:Company[];services:ServiceType[];can:(key:string)=>boolean;notify:(e:unknown)=>void;success:(message:string)=>void};
const now=new Date();const today=()=>new Date().toISOString().slice(0,10);
const escapeHtml=(value:unknown)=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]!));
const amountWords=(amount:number)=>`فقط ${Math.round(amount).toLocaleString('ar-IQ')} دينار عراقي لا غير`;

export function DashboardPage({companies,notify}:Props){
  const [year,setYear]=useState(now.getFullYear());const [month,setMonth]=useState(now.getMonth()+1);const [data,setData]=useState<any>();
  const load=()=>financialErpApi.dashboard(year,month).then(setData).catch(notify);useEffect(()=>{void load()},[year,month]);
  const max=Math.max(...(data?.by_company||[]).map((x:any)=>x.due),1);
  return <div className="space-y-4"><PageTitle title="لوحة المؤشرات" description="الاستحقاق المحاسبي منفصل عن المقبوض الفعلي والمصروفات للفترة المختارة."/>
    <Card><CardContent className="p-3 flex gap-2 items-end"><Field label="السنة"><Input className="w-28" type="number" value={year} onChange={e=>setYear(Number(e.target.value))}/></Field><Field label="الشهر"><Input className="w-24" type="number" min={1} max={12} value={month} onChange={e=>setMonth(Number(e.target.value))}/></Field><Button variant="outline" onClick={load}>تحديث</Button></CardContent></Card>
    <div className="grid grid-cols-2 xl:grid-cols-5 gap-3">{[['المستحق المتراكم',data?.accrued_revenue,'text-blue-700'],['المقبوض الفعلي',data?.actual_revenue,'text-emerald-700'],['المصاريف',data?.expenses,'text-red-700'],['الربح التقديري',data?.estimated_profit,'text-violet-700'],['الرصيد القائم',data?.outstanding_receivable,'text-amber-700']].map(([label,value,color])=><Card key={label as string}><CardContent className="p-4"><p className="text-xs text-slate-500">{label}</p><b className={`block text-xl mt-1 ${color}`}>{money(value as number)}</b></CardContent></Card>)}</div>
    <div className="grid lg:grid-cols-2 gap-4"><Card><CardHeader><CardTitle className="text-base">الشركات حسب استحقاق MFEC</CardTitle></CardHeader><CardContent className="space-y-3">{data?.by_company?.slice(0,10).map((x:any)=><div key={x.name}><div className="flex justify-between text-sm mb-1"><span>{x.name}</span><b>{money(x.due)}</b></div><Progress value={x.due/max*100}/></div>)}{!data?.by_company?.length&&<Empty/>}</CardContent></Card>
      <Card><CardHeader><CardTitle className="text-base">ملخص أنواع الخدمات</CardTitle></CardHeader><CardContent>{data?.by_service?.map((x:any)=><div key={x.name} className="grid grid-cols-3 py-3 border-t"><b>{x.name}</b><span>{money(x.gross)}</span><span className="font-bold">{money(x.due)}</span></div>)}{!data?.by_service?.length&&<Empty/>}</CardContent></Card></div>
    <Card><CardContent className="p-4 grid md:grid-cols-3 gap-4"><Metric label="حجم أعمال الأعضاء" value={data?.gross_business_amount}/><Metric label="صافي النتيجة الفعلية" value={data?.actual_net_result}/><Metric label="عدد الشركات المعرفة" value={companies.length} moneyValue={false}/></CardContent></Card>
  </div>;
}

const blankRevenue={receipt_number:'',company_id:'',received_at:today(),amount:'',receipt_method:'تحويل مصرفي',category:'اشتراك/خدمة',description:'',period_start:'',period_end:'',notes:'',attachment_key:''};
export function RevenuesPage({companies,can,notify,success}:Props){
  const {brand,resolveAssetUrl}=useBrand();
  const [rows,setRows]=useState<Revenue[]>([]);const [company,setCompany]=useState('');const [from,setFrom]=useState('');const [to,setTo]=useState('');const [deleted,setDeleted]=useState(false);
  const [selected,setSelected]=useState<number[]>([]);
  const [open,setOpen]=useState(false);const [edit,setEdit]=useState<Revenue>();const [form,setForm]=useState<any>(blankRevenue);const [preview,setPreview]=useState<Revenue>();
  const [allocationOpen,setAllocationOpen]=useState(false);const [receipt,setReceipt]=useState<Revenue>();const [targets,setTargets]=useState<any>({statements:[],settlements:[]});const [allocation,setAllocation]=useState({target_type:'statement',target_id:'',amount:''});
  const load=()=>financialErpApi.revenues({company_id:company,date_from:from,date_to:to,include_deleted:deleted}).then(x=>setRows(x.items)).catch(notify);useEffect(()=>{void load()},[deleted]);
  const save=async()=>{if(!form.receipt_number?.trim()){notify(new Error('رقم وصل القبض مطلوب'));return}if(!form.company_id){notify(new Error('اختر الشركة التي تم استلام المبلغ منها'));return}if(!form.received_at){notify(new Error('تاريخ القبض مطلوب'));return}if(!(Number(form.amount)>0)){notify(new Error('أدخل مبلغ قبض أكبر من صفر'));return}if(!form.description?.trim()){notify(new Error('بيان الإيراد مطلوب'));return}try{const payload={...form,company_id:Number(form.company_id),amount:Number(form.amount),period_start:form.period_start||null,period_end:form.period_end||null};if(edit)await financialErpApi.updateRevenue(edit.id,payload);else await financialErpApi.createRevenue(payload);setOpen(false);await load();success(edit?'تم تعديل وصل القبض':'تم حفظ وصل القبض الإلكتروني')}catch(e){notify(e)}};
  const openEdit=(x?:Revenue)=>{setEdit(x);setForm(x?{...blankRevenue,...x,company_id:String(x.company_id),amount:String(x.amount)}:blankRevenue);setOpen(true)};
  const openAllocation=async(x:Revenue)=>{try{setReceipt(x);setTargets(await financialErpApi.allocationTargets(x.id));setAllocation({target_type:'statement',target_id:'',amount:String(x.remaining)});setAllocationOpen(true)}catch(e){notify(e)}};
  const allocate=async()=>{if(!receipt)return;try{await financialErpApi.allocateRevenue(receipt.id,{statement_id:allocation.target_type==='statement'?Number(allocation.target_id):null,settlement_batch_id:allocation.target_type==='settlement'?Number(allocation.target_id):null,amount:Number(allocation.amount)});setAllocationOpen(false);await load()}catch(e){notify(e)}};
  const printReceipt=(row:Revenue)=>{const companyName=companies.find(c=>c.id===row.company_id)?.name||'-';const logo=resolveAssetUrl(brand.report_logo||brand.system_logo);const w=window.open('','_blank','noopener,noreferrer,width=900,height=900');if(!w)return;w.document.write(`<!doctype html><html dir="rtl"><head><meta charset="utf-8"><title>وصل ${escapeHtml(row.receipt_number)}</title><style>body{font-family:Tahoma,Arial;padding:35px;color:#172033}.sheet{border:2px solid #1e506b;padding:28px;max-width:760px;margin:auto}.head{display:flex;justify-content:space-between;align-items:center;border-bottom:2px solid #1e506b;padding-bottom:16px}.head img{width:90px;height:90px;object-fit:contain}h1{text-align:center}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin:24px 0}.field{border-bottom:1px solid #bbb;padding:10px}.amount{font-size:22px;font-weight:bold}.sign{margin-top:55px;display:flex;justify-content:space-between}@media print{button{display:none}.sheet{border-color:#000}}</style></head><body><div class="sheet"><div class="head"><img src="${escapeHtml(logo)}"><div><b>${escapeHtml(brand.system_name)}</b><p>${escapeHtml(brand.org_abbr||'MFEC')}</p></div><div>رقم الوصل<br><b>${escapeHtml(row.receipt_number)}</b></div></div><h1>وصل قبض إلكتروني</h1><div class="grid"><div class="field">استلمنا من: <b>${escapeHtml(companyName)}</b></div><div class="field">التاريخ: <b>${escapeHtml(row.received_at)}</b></div><div class="field amount">المبلغ: ${escapeHtml(money(row.amount))}</div><div class="field">طريقة الدفع: ${escapeHtml(row.receipt_method)}</div><div class="field">الفترة: ${escapeHtml(row.period_start||'-')} — ${escapeHtml(row.period_end||'-')}</div><div class="field">أنشأ الوصل: ${escapeHtml(row.created_by||'-')}</div></div><p><b>المبلغ كتابة:</b> ${escapeHtml(amountWords(row.amount))}</p><p><b>البيان:</b> ${escapeHtml(row.description)}</p><p><b>ملاحظات:</b> ${escapeHtml(row.notes||'-')}</p><div class="sign"><span>توقيع المستلم: __________</span><span>الختم/الاعتماد: __________</span></div><button onclick="window.print()">طباعة / حفظ PDF</button></div></body></html>`);w.document.close()};
  return <div className="space-y-4"><PageTitle title="الإيرادات الفعلية" description="وصولات القبض الفعلية وتخصيصها الجزئي على كشف أو دفعة تسوية لنفس الشركة."
    actions={<>{can('financial.revenues.create')&&<Button onClick={()=>openEdit()}><Plus className="w-4 h-4 ml-2"/>وصل قبض</Button>}{can('financial.reports.xlsx')&&<Button variant="outline" onClick={()=>financialErpApi.exportRevenues({company_id:company,date_from:from,date_to:to,selected_ids:selected.length?selected:undefined}).catch(notify)}><FileSpreadsheet className="w-4 h-4 ml-1"/>Excel</Button>}<Button variant="outline" onClick={()=>window.print()}><Printer className="w-4 h-4 ml-1"/>طباعة/PDF</Button></>}/>
    <Card><CardContent className="p-3 flex gap-2 flex-wrap"><select className="h-10 border rounded-md px-3" value={company} onChange={e=>setCompany(e.target.value)}><option value="">كل الشركات</option>{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><SafeDateInput className="w-40" value={from} onChange={e=>setFrom(e.target.value)}/><SafeDateInput className="w-40" value={to} onChange={e=>setTo(e.target.value)}/><Button type="button" variant="outline" onClick={load}>تطبيق</Button>{can('financial.revenues.restore')&&<label className="flex gap-2 items-center text-sm"><input type="checkbox" checked={deleted} onChange={e=>setDeleted(e.target.checked)}/>إظهار المحذوف</label>}</CardContent></Card>
    <div className="grid sm:grid-cols-3 gap-2"><Metric label="إجمالي المقبوض" value={rows.filter(x=>!x.deleted).reduce((a,x)=>a+x.amount,0)}/><Metric label="المخصص" value={rows.reduce((a,x)=>a+x.allocated,0)}/><Metric label="غير المخصص" value={rows.reduce((a,x)=>a+x.remaining,0)}/></div>
    <CompactTable headers={['','رقم الوصل','الشركة','التاريخ','المبلغ','الطريقة/التصنيف','المخصص','المتبقي','الإجراءات']}>{rows.map(x=><tr key={x.id} className={`border-t ${x.deleted?'opacity-50':''} ${selected.length&&!selected.includes(x.id)?'print:hidden':''}`}><td className="p-3 print:hidden"><Checkbox checked={selected.includes(x.id)} onCheckedChange={v=>setSelected(ids=>v?[...ids,x.id]:ids.filter(id=>id!==x.id))}/></td><td className="p-3 font-mono">{x.receipt_number}</td><td>{companies.find(c=>c.id===x.company_id)?.name}</td><td>{x.received_at}</td><td>{money(x.amount)}</td><td>{x.receipt_method}<small className="block">{x.category}</small></td><td>{money(x.allocated)}</td><td>{money(x.remaining)}</td><td><Button type="button" size="icon" variant="ghost" title="معاينة الوصل" onClick={()=>setPreview(x)}><ReceiptText className="w-4 h-4"/></Button>{x.attachment_key&&<Button size="icon" variant="ghost" onClick={()=>financialErpApi.openDocument(x.attachment_key!)}><Eye className="w-4 h-4"/></Button>}{!x.deleted&&x.remaining>0&&can('financial.revenues.edit')&&<Button size="sm" variant="outline" onClick={()=>openAllocation(x)}><Wallet className="w-4 h-4 ml-1"/>تخصيص</Button>}{!x.deleted&&can('financial.revenues.edit')&&<Button size="icon" variant="ghost" onClick={()=>openEdit(x)}><Edit3 className="w-4 h-4"/></Button>}{!x.deleted&&can('financial.revenues.delete')&&<Button size="icon" variant="ghost" onClick={async()=>{await financialErpApi.deleteRevenue(x.id);await load()}}><Trash2 className="w-4 h-4 text-red-600"/></Button>}{x.deleted&&can('financial.revenues.restore')&&<Button size="sm" variant="outline" onClick={async()=>{await financialErpApi.restoreRevenue(x.id);await load()}}><RotateCcw className="w-4 h-4 ml-1"/>استعادة</Button>}</td></tr>)}</CompactTable>
    <FormDialog open={open} onOpenChange={setOpen} title={edit?'تعديل وصل القبض':'وصل قبض جديد'}><div className="grid md:grid-cols-2 gap-3"><Field label="رقم الوصل"><Input value={form.receipt_number} onChange={e=>setForm({...form,receipt_number:e.target.value})}/></Field><Field label="الشركة"><select className="h-10 border rounded-md px-3 w-full" value={form.company_id} onChange={e=>setForm({...form,company_id:e.target.value})}><option value="">اختر</option>{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="التاريخ"><SafeDateInput value={form.received_at} onChange={e=>setForm({...form,received_at:e.target.value})}/></Field><Field label="المبلغ"><Input type="number" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></Field><Field label="طريقة القبض"><Input value={form.receipt_method} onChange={e=>setForm({...form,receipt_method:e.target.value})}/></Field><Field label="التصنيف"><Input value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></Field><Field label="وصف الإيراد" className="md:col-span-2"><Input value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></Field><Field label="من فترة"><SafeDateInput value={form.period_start} onChange={e=>setForm({...form,period_start:e.target.value})}/></Field><Field label="إلى فترة"><SafeDateInput value={form.period_end} onChange={e=>setForm({...form,period_end:e.target.value})}/></Field><Field label="المرفق"><FileButton label={form.attachment_key?'تم رفع الوصل':'رفع الوصل'} onFile={async file=>{const u=await financialErpApi.upload('receipts',file);setForm({...form,attachment_key:u.object_key})}}/></Field><Field label="ملاحظات"><Textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></Field></div><Button type="button" onClick={save}>حفظ الوصل</Button></FormDialog>
    <FormDialog open={allocationOpen} onOpenChange={setAllocationOpen} title={`تخصيص الوصل ${receipt?.receipt_number||''}`}><p>الرصيد المتاح: <b>{money(receipt?.remaining)}</b></p><div className="grid md:grid-cols-2 gap-3"><Field label="نوع الهدف"><select className="h-10 border rounded-md px-3 w-full" value={allocation.target_type} onChange={e=>setAllocation({...allocation,target_type:e.target.value,target_id:''})}><option value="statement">كشف شهري معتمد</option><option value="settlement">دفعة تسوية</option></select></Field><Field label="الهدف"><select className="h-10 border rounded-md px-3 w-full" value={allocation.target_id} onChange={e=>setAllocation({...allocation,target_id:e.target.value})}><option value="">اختر</option>{(allocation.target_type==='statement'?targets.statements:targets.settlements).map((x:any)=><option key={x.id} value={x.id}>{x.label}</option>)}</select></Field><Field label="مبلغ التخصيص"><Input type="number" max={receipt?.remaining} value={allocation.amount} onChange={e=>setAllocation({...allocation,amount:e.target.value})}/></Field></div><Button type="button" onClick={allocate} disabled={!allocation.target_id}>حفظ التخصيص الجزئي</Button></FormDialog>
    <FormDialog open={!!preview} onOpenChange={value=>!value&&setPreview(undefined)} title={`معاينة وصل ${preview?.receipt_number||''}`} className="max-w-3xl"><div className="border-2 rounded-xl p-6 bg-white"><div className="flex justify-between border-b-2 pb-3"><img className="w-20 h-20 object-contain" src={resolveAssetUrl(brand.report_logo||brand.system_logo)} alt="MFEC"/><div className="text-center"><b>{brand.system_name}</b><h3 className="text-xl font-bold mt-2">وصل قبض إلكتروني</h3></div><div className="font-mono">{preview?.receipt_number}</div></div>{preview&&<div className="grid md:grid-cols-2 gap-3 mt-5"><p>الشركة: <b>{companies.find(c=>c.id===preview.company_id)?.name}</b></p><p>التاريخ: <b>{preview.received_at}</b></p><p>المبلغ: <b>{money(preview.amount)}</b></p><p>طريقة الدفع: <b>{preview.receipt_method}</b></p><p className="md:col-span-2">المبلغ كتابة: {amountWords(preview.amount)}</p><p className="md:col-span-2">البيان: {preview.description}</p></div>}</div>{preview&&<Button type="button" onClick={()=>printReceipt(preview)}><Printer className="w-4 h-4 ml-2"/>طباعة / حفظ PDF</Button>}</FormDialog>
  </div>;
}

const blankExpense={expense_date:today(),category:'',description:'',amount:'',notes:'',receipt_key:''};
export function ExpensesPage({can,notify,success}:Props){
  const [year,setYear]=useState<number|''>(now.getFullYear());const [month,setMonth]=useState<number|''>(now.getMonth()+1);const [from,setFrom]=useState('');const [to,setTo]=useState('');const [rows,setRows]=useState<Expense[]>([]);const [deleted,setDeleted]=useState(false);const [open,setOpen]=useState(false);const [edit,setEdit]=useState<Expense>();const [form,setForm]=useState<any>(blankExpense);
  const [selected,setSelected]=useState<number[]>([]);
  const load=()=>financialErpApi.expenses({accounting_year:year,accounting_month:month,date_from:from,date_to:to,include_deleted:deleted}).then(x=>setRows(x.items)).catch(notify);useEffect(()=>{void load()},[year,month,from,to,deleted]);
  const save=async()=>{if(!form.expense_date){notify(new Error('تاريخ المصروف مطلوب'));return}if(form.category.trim().length<2){notify(new Error('تصنيف المصروف مطلوب'));return}if(form.description.trim().length<2){notify(new Error('بيان المصروف مطلوب'));return}if(!(Number(form.amount)>0)){notify(new Error('أدخل مبلغًا أكبر من صفر'));return}try{const d=new Date(`${form.expense_date}T00:00:00`);await financialErpApi.saveExpense({...form,amount:Number(form.amount),accounting_year:year||d.getFullYear(),accounting_month:month||d.getMonth()+1},edit?.id);setOpen(false);await load();success(edit?'تم تعديل المصروف':'تم حفظ المصروف')}catch(e){notify(e)}};
  const openEdit=(x?:Expense)=>{setEdit(x);setForm(x?{...blankExpense,...x,amount:String(x.amount)}:blankExpense);setOpen(true)};
  return <div className="space-y-4"><PageTitle title="المصاريف" description="سجل المصروفات مع إيصالاتها، التعديل، الحذف المنطقي والاستعادة."
    actions={<>{can('financial.expenses.create')&&<Button onClick={()=>openEdit()}><Plus className="w-4 h-4 ml-1"/>مصروف</Button>}{can('financial.reports.xlsx')&&<Button variant="outline" onClick={()=>financialErpApi.exportExpenses({accounting_year:year,accounting_month:month,date_from:from,date_to:to,selected_ids:selected.length?selected:undefined}).catch(notify)}><FileSpreadsheet className="w-4 h-4 ml-1"/>Excel</Button>}<Button variant="outline" onClick={()=>window.print()}><Printer className="w-4 h-4 ml-1"/>كشف/PDF</Button></>}/>
    <Card><CardContent className="p-3 flex gap-2 items-end flex-wrap"><Field label="السنة"><Input className="w-28" type="number" value={year} onChange={e=>setYear(e.target.value?Number(e.target.value):'')}/></Field><Field label="الشهر"><Input className="w-24" type="number" value={month} onChange={e=>setMonth(e.target.value?Number(e.target.value):'')}/></Field><Field label="من تاريخ"><SafeDateInput className="w-40" value={from} onChange={e=>{setFrom(e.target.value);setYear('');setMonth('')}}/></Field><Field label="إلى تاريخ"><SafeDateInput className="w-40" value={to} onChange={e=>{setTo(e.target.value);setYear('');setMonth('')}}/></Field>{can('financial.expenses.restore')&&<label className="flex gap-2 items-center pb-2"><input type="checkbox" checked={deleted} onChange={e=>setDeleted(e.target.checked)}/>إظهار المحذوف</label>}</CardContent></Card>
    <Card><CardContent className="p-4"><small>إجمالي مصاريف الفترة</small><b className="block text-2xl text-red-700">{money(rows.filter(x=>!x.deleted).reduce((a,x)=>a+x.amount,0))}</b></CardContent></Card>
    <CompactTable headers={['','التاريخ','التصنيف','الوصف','المبلغ','المستخدم','الإيصال','الإجراءات']}>{rows.map(x=><tr key={x.id} className={`border-t ${x.deleted?'opacity-50':''} ${selected.length&&!selected.includes(x.id)?'print:hidden':''}`}><td className="p-3 print:hidden"><Checkbox checked={selected.includes(x.id)} onCheckedChange={v=>setSelected(ids=>v?[...ids,x.id]:ids.filter(id=>id!==x.id))}/></td><td className="p-3">{x.expense_date}</td><td>{x.category}</td><td className="max-w-72 whitespace-normal">{x.description}<small className="block">{x.notes}</small></td><td>{money(x.amount)}</td><td>{x.created_by}</td><td>{x.receipt_key&&<><Button size="icon" variant="ghost" onClick={()=>financialErpApi.openDocument(x.receipt_key!)}><Eye className="w-4 h-4"/></Button><Button size="icon" variant="ghost" onClick={()=>financialErpApi.openDocument(x.receipt_key!,`expense-${x.id}`)}><Download className="w-4 h-4"/></Button></>}</td><td>{!x.deleted&&can('financial.expenses.edit')&&<Button size="icon" variant="ghost" onClick={()=>openEdit(x)}><Edit3 className="w-4 h-4"/></Button>}{!x.deleted&&can('financial.expenses.delete')&&<Button size="icon" variant="ghost" onClick={async()=>{await financialErpApi.deleteExpense(x.id);await load()}}><Trash2 className="w-4 h-4 text-red-600"/></Button>}{x.deleted&&can('financial.expenses.restore')&&<Button size="sm" variant="outline" onClick={async()=>{await financialErpApi.restoreExpense(x.id);await load()}}><RotateCcw className="w-4 h-4 ml-1"/>استعادة</Button>}</td></tr>)}</CompactTable>
    <FormDialog open={open} onOpenChange={setOpen} title={edit?'تعديل المصروف':'إضافة مصروف'}><div className="grid md:grid-cols-2 gap-3"><Field label="التاريخ"><SafeDateInput value={form.expense_date} onChange={e=>setForm({...form,expense_date:e.target.value})}/></Field><Field label="التصنيف"><Input value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></Field><Field label="الوصف"><Input value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></Field><Field label="المبلغ"><Input type="number" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></Field><Field label="الملاحظات"><Textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></Field><Field label="وصل المصروف"><FileButton label={form.receipt_key?'تم رفع الوصل':'رفع الوصل'} onFile={async file=>{const u=await financialErpApi.upload('receipts',file);setForm({...form,receipt_key:u.object_key})}}/></Field></div><Button type="button" onClick={save}>حفظ المصروف</Button></FormDialog>
  </div>;
}

function Field({label,children,className=''}:{label:string;children:React.ReactNode;className?:string}){return <div className={className}><Label className="block mb-1">{label}</Label>{children}</div>}
function Metric({label,value,moneyValue=true}:{label:string;value:number;moneyValue?:boolean}){return <Card><CardContent className="p-4"><small className="text-slate-500">{label}</small><b className="block text-xl">{moneyValue?money(value):Number(value||0).toLocaleString('ar-IQ')}</b></CardContent></Card>}
