import { useEffect, useState } from 'react';
import { Edit3, Eye, FileSpreadsheet, Plus, Printer, ReceiptText, RotateCcw, Save, Wallet } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Checkbox } from '@/components/ui/checkbox';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Progress } from '@/components/ui/progress';
import { Textarea } from '@/components/ui/textarea';
import { financialErpApi } from '@/lib/financialErpApi';
import { useBrand } from '@/lib/brand';
import type { Company, Expense, Revenue, ServiceType } from '@/types/financialErp';
import { CompactTable, Empty, FileButton, FormDialog, PageTitle, SafeDateInput, StatusBadge, money } from './FinancialUi';

type Props={companies:Company[];services:ServiceType[];can:(key:string)=>boolean;notify:(e:unknown)=>void;success:(message:string)=>void};
const now=new Date();const today=()=>new Date().toISOString().slice(0,10);
const escapeHtml=(value:unknown)=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]!));
const amountWords=(amount:number)=>`فقط ${Math.round(amount).toLocaleString('ar-IQ')} دينار عراقي لا غير`;

export function DashboardPage({companies,notify}:Props){
  const [year,setYear]=useState(now.getFullYear());const [month,setMonth]=useState(now.getMonth()+1);const [data,setData]=useState<any>();
  const load=()=>financialErpApi.dashboard(year,month).then(setData).catch(notify);useEffect(()=>{void load()},[year,month]);
  const max=Math.max(...(data?.by_company||[]).map((x:any)=>x.due),1);
  return <div className="space-y-4"><PageTitle title="لوحة المؤشرات" description="الاستحقاق المحاسبي منفصل عن المقبوض الفعلي والمصروفات للفترة المختارة."/>
    <Card><CardContent className="p-3 flex gap-2 items-end"><Field label="السنة"><Input className="w-28" type="number" value={year} onChange={e=>setYear(Number(e.target.value))}/></Field><Field label="الشهر"><Input className="w-24" type="number" min={1} max={12} value={month} onChange={e=>setMonth(Number(e.target.value))}/></Field><Button variant="outline" onClick={load}>تحديث</Button></CardContent></Card>
    <div className="grid grid-cols-2 xl:grid-cols-5 gap-3">{[['المستحق المتراكم',data?.accrued_revenue,'text-blue-700'],['المقبوض الفعلي',data?.actual_revenue,'text-emerald-700'],['المصاريف',data?.expenses,'text-red-700'],['الربح التقديري',data?.estimated_profit,'text-violet-700'],['الرصيد القائم',data?.outstanding_receivable,'text-amber-700']].map(([label,value,color])=><Card key={label as string}><CardContent className="p-4"><p className="text-xs text-slate-500">{label}</p><b className={`block text-xl mt-1 ${color}`}>{money(value as number)}</b></CardContent></Card>)}</div>
    <div className="grid lg:grid-cols-2 gap-4"><Card><CardHeader><CardTitle className="text-base">الشركات حسب استحقاق MFEC</CardTitle></CardHeader><CardContent className="space-y-3">{data?.by_company?.slice(0,10).map((x:any)=><div key={x.name}><div className="flex justify-between text-sm mb-1"><span>{x.name}</span><b>{money(x.due)}</b></div><Progress value={x.due/max*100}/></div>)}{!data?.by_company?.length&&<Empty/>}</CardContent></Card>
      <Card><CardHeader><CardTitle className="text-base">ملخص أنواع الخدمات</CardTitle></CardHeader><CardContent>{data?.by_service?.map((x:any)=><div key={x.name} className="grid grid-cols-3 py-3 border-t"><b>{x.name}</b><span>{money(x.gross)}</span><span className="font-bold">{money(x.due)}</span></div>)}{!data?.by_service?.length&&<Empty/>}</CardContent></Card></div>
    <Card><CardContent className="p-4 grid md:grid-cols-3 gap-4"><Metric label="حجم أعمال الأعضاء" value={data?.gross_business_amount}/><Metric label="صافي النتيجة الفعلية" value={data?.actual_net_result}/><Metric label="عدد الشركات المعرفة" value={companies.length} moneyValue={false}/></CardContent></Card>
  </div>;
}

const blankRevenue={company_id:'',received_at:today(),amount:'',receipt_method:'تحويل مصرفي',category:'اشتراك/خدمة',description:'',period_start:'',period_end:'',notes:'',attachment_key:''};
export function RevenuesPage({companies,can,notify,success}:Props){
  const {brand,resolveAssetUrl}=useBrand();
  const [rows,setRows]=useState<Revenue[]>([]);const [company,setCompany]=useState('');const [from,setFrom]=useState('');const [to,setTo]=useState('');const [deleted,setDeleted]=useState(false);
  const [selected,setSelected]=useState<number[]>([]);
  const [open,setOpen]=useState(false);const [edit,setEdit]=useState<Revenue>();const [form,setForm]=useState<any>(blankRevenue);
  const [previewForm,setPreviewForm]=useState(false);const [preview,setPreview]=useState<Revenue>();
  const [allocationOpen,setAllocationOpen]=useState(false);const [receipt,setReceipt]=useState<Revenue>();const [targets,setTargets]=useState<any>({statements:[],settlements:[]});const [allocation,setAllocation]=useState({target_type:'statement',target_id:'',amount:''});
  const [voucher,setVoucher]=useState<{next_rec:number;preview_rec:string}|null>(null);const [nextRecInput,setNextRecInput]=useState('');
  const loadVoucher=()=>financialErpApi.voucherNumbers().then(x=>{setVoucher({next_rec:x.next_rec,preview_rec:x.preview_rec});setNextRecInput(String(x.next_rec))}).catch(notify);
  const load=()=>financialErpApi.revenues({company_id:company,date_from:from,date_to:to,include_deleted:deleted}).then(x=>setRows(x.items)).catch(notify);
  useEffect(()=>{void load();void loadVoucher()},[deleted]);
  const save=async()=>{if(!form.company_id){notify(new Error('اختر الشركة التي تم استلام المبلغ منها'));return}if(!form.received_at){notify(new Error('تاريخ القبض مطلوب'));return}if(!(Number(form.amount)>0)){notify(new Error('أدخل مبلغ قبض أكبر من صفر'));return}if(!form.description?.trim()){notify(new Error('بيان الإيراد مطلوب'));return}try{const payload={company_id:Number(form.company_id),received_at:form.received_at,amount:Number(form.amount),receipt_method:form.receipt_method,category:form.category||null,description:form.description,period_start:form.period_start||null,period_end:form.period_end||null,notes:form.notes||null,attachment_key:form.attachment_key||null};let saved:Revenue|undefined;if(edit){const x=await financialErpApi.updateRevenue(edit.id,payload);saved={...edit,...payload,receipt_number:x.receipt_number,amount:Number(form.amount),allocated:edit.allocated,remaining:edit.remaining,deleted:false,status:'active'};success(`تم تعديل وصل القبض ${x.receipt_number}`)}else{const x=await financialErpApi.createRevenue(payload);saved={id:x.id,receipt_number:x.receipt_number,company_id:Number(form.company_id),received_at:form.received_at,amount:Number(form.amount),allocated:0,remaining:Number(form.amount),receipt_method:form.receipt_method,category:form.category,description:form.description,period_start:form.period_start||undefined,period_end:form.period_end||undefined,notes:form.notes||undefined,attachment_key:form.attachment_key||undefined,deleted:false,status:'active'};success(`تم حفظ وصل القبض ${x.receipt_number}`)}setOpen(false);setPreviewForm(false);await load();await loadVoucher();if(saved){setPreview(saved);printReceipt(saved)}}catch(e){notify(e)}};
  const openEdit=(x?:Revenue)=>{setEdit(x);setForm(x?{...blankRevenue,...x,company_id:String(x.company_id),amount:String(x.amount),period_start:x.period_start||'',period_end:x.period_end||'',notes:x.notes||'',attachment_key:x.attachment_key||''}:blankRevenue);setPreviewForm(false);setOpen(true);void loadVoucher()};
  const openAllocation=async(x:Revenue)=>{try{setReceipt(x);setTargets(await financialErpApi.allocationTargets(x.id));setAllocation({target_type:'statement',target_id:'',amount:String(x.remaining)});setAllocationOpen(true)}catch(e){notify(e)}};
  const allocate=async()=>{if(!receipt)return;try{await financialErpApi.allocateRevenue(receipt.id,{statement_id:allocation.target_type==='statement'?Number(allocation.target_id):null,settlement_batch_id:allocation.target_type==='settlement'?Number(allocation.target_id):null,amount:Number(allocation.amount)});setAllocationOpen(false);await load()}catch(e){notify(e)}};
  const draftPreview=():Revenue=>({id:edit?.id||0,receipt_number:edit?.receipt_number||voucher?.preview_rec||'REC-…',company_id:Number(form.company_id)||0,received_at:form.received_at,amount:Number(form.amount)||0,allocated:edit?.allocated||0,remaining:Number(form.amount)||0,receipt_method:form.receipt_method,category:form.category,description:form.description,period_start:form.period_start||undefined,period_end:form.period_end||undefined,notes:form.notes||undefined,attachment_key:form.attachment_key||undefined,deleted:false,status:'active'});
  const printReceipt=(row:Revenue)=>{const companyName=companies.find(c=>c.id===row.company_id)?.name||'-';const logo=resolveAssetUrl(brand.report_logo||brand.system_logo);const w=window.open('','_blank','noopener,noreferrer,width=900,height=900');if(!w)return;w.document.write(`<!doctype html><html dir="rtl"><head><meta charset="utf-8"><title>وصل ${escapeHtml(row.receipt_number)}</title><style>body{font-family:Tahoma,Arial;padding:28px;color:#172033;background:#f5f7fa}.sheet{border:2px solid #1e506b;padding:28px;max-width:760px;margin:auto;background:#fff}.head{display:flex;justify-content:space-between;align-items:center;border-bottom:2px solid #1e506b;padding-bottom:16px}.head img{width:90px;height:90px;object-fit:contain}h1{text-align:center;margin:18px 0}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin:24px 0}.field{border-bottom:1px solid #bbb;padding:10px}.amount{font-size:22px;font-weight:bold}.sign{margin-top:55px;display:flex;justify-content:space-between}.foot{margin-top:24px;font-size:12px;color:#555;text-align:center}@media print{button{display:none}body{background:#fff}}</style></head><body><div class="sheet"><div class="head"><img src="${escapeHtml(logo)}"><div><b>${escapeHtml(brand.system_name)}</b><p>${escapeHtml(brand.org_abbr||'MFEC')}</p><small>${escapeHtml(brand.company_name||'')}</small></div><div>رقم الوصل<br><b>${escapeHtml(row.receipt_number)}</b></div></div><h1>وصل قبض إلكتروني</h1><div class="grid"><div class="field">استلمنا من: <b>${escapeHtml(companyName)}</b></div><div class="field">التاريخ: <b>${escapeHtml(row.received_at)}</b></div><div class="field amount">المبلغ: ${escapeHtml(money(row.amount))}</div><div class="field">طريقة القبض: ${escapeHtml(row.receipt_method)}</div><div class="field">التصنيف: ${escapeHtml(row.category||'-')}</div><div class="field">الفترة: ${escapeHtml(row.period_start||'-')} — ${escapeHtml(row.period_end||'-')}</div></div><p><b>المبلغ كتابة:</b> ${escapeHtml(amountWords(row.amount))}</p><p><b>وصف الإيراد:</b> ${escapeHtml(row.description)}</p><p><b>ملاحظات:</b> ${escapeHtml(row.notes||'-')}</p><div class="sign"><span>توقيع المستلم: __________</span><span>الختم/الاعتماد: __________</span></div><div class="foot">${escapeHtml(brand.footer_text||'')}<br>${escapeHtml(brand.phone||'')} · ${escapeHtml(brand.email||'')}</div><button onclick="window.print()">طباعة / حفظ PDF</button></div></body></html>`);w.document.close()};
  const saveNextRec=async()=>{const n=Number(nextRecInput);if(!(n>0)){notify(new Error('أدخل رقمًا صحيحًا لتالي وصل القبض'));return}try{const x=await financialErpApi.setVoucherNumbers({next_rec:n});setVoucher({next_rec:x.next_rec,preview_rec:x.preview_rec});setNextRecInput(String(x.next_rec));success(`تم تعيين الرقم التالي لوصل القبض: ${x.preview_rec}`)}catch(e){notify(e)}};
  return <div className="space-y-4"><PageTitle title="وصولات القبض" description="ترقيم تلقائي REC-xxxx يُحجز فقط عند الحفظ الناجح. الإلغاء يبقي الرقم للتدقيق ولا يعيده للمخزون."
    actions={<>{can('financial.revenues.create')&&<Button onClick={()=>openEdit()}><Plus className="w-4 h-4 ml-2"/>وصل قبض</Button>}{can('financial.reports.xlsx')&&<Button variant="outline" onClick={()=>financialErpApi.exportRevenues({company_id:company,date_from:from,date_to:to,selected_ids:selected.length?selected:undefined}).catch(notify)}><FileSpreadsheet className="w-4 h-4 ml-1"/>Excel</Button>}</>}/>
    <Card><CardContent className="p-3 flex flex-wrap gap-3 items-end"><Field label="رقم وصل القبض التالي"><div className="flex gap-2"><Input className="w-36 font-mono" value={nextRecInput} onChange={e=>setNextRecInput(e.target.value)} placeholder="5"/><Button type="button" variant="outline" onClick={()=>void saveNextRec()}>حفظ</Button></div></Field><div className="text-sm text-slate-600 pb-2">المعاينة: <b className="font-mono">{voucher?.preview_rec||'—'}</b> — لا يُستهلك عند المعاينة أو فتح النموذج</div></CardContent></Card>
    <Card><CardContent className="p-3 flex gap-2 flex-wrap"><select className="h-10 border rounded-md px-3" value={company} onChange={e=>setCompany(e.target.value)}><option value="">كل الشركات</option>{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><SafeDateInput className="w-40" value={from} onChange={e=>setFrom(e.target.value)}/><SafeDateInput className="w-40" value={to} onChange={e=>setTo(e.target.value)}/><Button type="button" variant="outline" onClick={load}>تطبيق</Button>{can('financial.revenues.restore')&&<label className="flex gap-2 items-center text-sm"><input type="checkbox" checked={deleted} onChange={e=>setDeleted(e.target.checked)}/>إظهار الملغى</label>}</CardContent></Card>
    <div className="grid sm:grid-cols-3 gap-2"><Metric label="إجمالي المقبوض" value={rows.filter(x=>!x.deleted).reduce((a,x)=>a+x.amount,0)}/><Metric label="المخصص" value={rows.reduce((a,x)=>a+x.allocated,0)}/><Metric label="غير المخصص" value={rows.filter(x=>!x.deleted).reduce((a,x)=>a+x.remaining,0)}/></div>
    <CompactTable headers={['','رقم الوصل','الشركة','التاريخ','المبلغ','الطريقة/التصنيف','الحالة','الإجراءات']}>{rows.map(x=><tr key={x.id} className={`border-t ${x.deleted?'opacity-60':''}`}><td className="p-3 print:hidden"><Checkbox checked={selected.includes(x.id)} onCheckedChange={v=>setSelected(ids=>v?[...ids,x.id]:ids.filter(id=>id!==x.id))}/></td><td className="p-3 font-mono font-bold">{x.receipt_number}</td><td>{companies.find(c=>c.id===x.company_id)?.name}</td><td>{x.received_at}</td><td>{money(x.amount)}</td><td>{x.receipt_method}<small className="block">{x.category}</small></td><td><StatusBadge value={x.deleted||x.status==='cancelled'?'cancelled':'active'}/></td><td className="print:hidden"><Button type="button" size="icon" variant="ghost" title="معاينة/طباعة" onClick={()=>{setPreview(x);printReceipt(x)}}><Printer className="w-4 h-4"/></Button>{x.attachment_key&&<Button size="icon" variant="ghost" onClick={()=>financialErpApi.openDocument(x.attachment_key!)}><Eye className="w-4 h-4"/></Button>}{!x.deleted&&x.remaining>0&&can('financial.revenues.edit')&&<Button size="sm" variant="outline" onClick={()=>openAllocation(x)}><Wallet className="w-4 h-4 ml-1"/>تخصيص</Button>}{!x.deleted&&can('financial.revenues.edit')&&<Button size="icon" variant="ghost" onClick={()=>openEdit(x)}><Edit3 className="w-4 h-4"/></Button>}{!x.deleted&&can('financial.revenues.delete')&&<Button size="sm" variant="ghost" onClick={async()=>{if(!confirm(`إلغاء الوصل ${x.receipt_number}؟ سيبقى رقمه محجوزًا للتدقيق.`))return;await financialErpApi.deleteRevenue(x.id);await load();success(`تم إلغاء ${x.receipt_number}`)}}>إلغاء</Button>}{x.deleted&&can('financial.revenues.restore')&&<Button size="sm" variant="outline" onClick={async()=>{await financialErpApi.restoreRevenue(x.id);await load()}}><RotateCcw className="w-4 h-4 ml-1"/>إعادة تفعيل</Button>}</td></tr>)}</CompactTable>
    <FormDialog open={open} onOpenChange={setOpen} title={edit?`تعديل وصل ${edit.receipt_number}`:'وصل قبض جديد'} className="max-w-3xl"><div className="grid md:grid-cols-2 gap-3"><Field label="رقم الوصل"><Input className="font-mono font-bold" value={edit?.receipt_number||voucher?.preview_rec||'REC-…'} disabled/></Field><Field label="الشركة"><select className="h-10 border rounded-md px-3 w-full" value={form.company_id} onChange={e=>setForm({...form,company_id:e.target.value})}><option value="">اختر</option>{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="التاريخ"><SafeDateInput value={form.received_at} onChange={e=>setForm({...form,received_at:e.target.value})}/></Field><Field label="المبلغ"><Input type="number" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></Field><Field label="طريقة القبض"><Input value={form.receipt_method} onChange={e=>setForm({...form,receipt_method:e.target.value})}/></Field><Field label="التصنيف"><Input value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></Field><Field label="وصف الإيراد" className="md:col-span-2"><Input value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></Field><Field label="من فترة"><SafeDateInput value={form.period_start} onChange={e=>setForm({...form,period_start:e.target.value})}/></Field><Field label="إلى فترة"><SafeDateInput value={form.period_end} onChange={e=>setForm({...form,period_end:e.target.value})}/></Field><Field label="المرفق"><FileButton label={form.attachment_key?'تم رفع المرفق':'رفع مرفق'} onFile={async file=>{const u=await financialErpApi.upload('receipts',file);setForm({...form,attachment_key:u.object_key})}}/></Field><Field label="ملاحظات"><Textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></Field></div><div className="flex flex-wrap gap-2 mt-2"><Button type="button" variant="outline" onClick={()=>setPreviewForm(true)}><ReceiptText className="w-4 h-4 ml-2"/>معاينة الوصل</Button><Button type="button" onClick={()=>void save()}><Save className="w-4 h-4 ml-2"/>حفظ</Button></div></FormDialog>
    <FormDialog open={previewForm} onOpenChange={setPreviewForm} title="معاينة قبل الحفظ (لا تستهلك رقمًا)" className="max-w-3xl">{(()=>{const d=draftPreview();return <div className="space-y-3"><div className="border-2 rounded-xl p-6 bg-white"><div className="flex justify-between border-b-2 pb-3"><img className="w-20 h-20 object-contain" src={resolveAssetUrl(brand.report_logo||brand.system_logo)} alt="MFEC"/><div className="text-center"><b>{brand.system_name}</b><h3 className="text-xl font-bold mt-2">وصل قبض إلكتروني</h3></div><div className="font-mono">{d.receipt_number}</div></div><div className="grid md:grid-cols-2 gap-3 mt-5"><p>الشركة: <b>{companies.find(c=>c.id===d.company_id)?.name||'-'}</b></p><p>التاريخ: <b>{d.received_at||'-'}</b></p><p>المبلغ: <b>{money(d.amount)}</b></p><p>طريقة القبض: <b>{d.receipt_method}</b></p><p className="md:col-span-2">البيان: {d.description||'-'}</p></div></div><p className="text-sm text-amber-700">المعاينة لا تحجز الرقم. الحفظ فقط يستهلك {voucher?.preview_rec}.</p><Button type="button" onClick={()=>void save()}>تأكيد الحفظ</Button></div>})()}</FormDialog>
    <FormDialog open={allocationOpen} onOpenChange={setAllocationOpen} title={`تخصيص الوصل ${receipt?.receipt_number||''}`}><p>الرصيد المتاح: <b>{money(receipt?.remaining)}</b></p><div className="grid md:grid-cols-2 gap-3"><Field label="نوع الهدف"><select className="h-10 border rounded-md px-3 w-full" value={allocation.target_type} onChange={e=>setAllocation({...allocation,target_type:e.target.value,target_id:''})}><option value="statement">كشف شهري معتمد</option><option value="settlement">دفعة تسوية</option></select></Field><Field label="الهدف"><select className="h-10 border rounded-md px-3 w-full" value={allocation.target_id} onChange={e=>setAllocation({...allocation,target_id:e.target.value})}><option value="">اختر</option>{(allocation.target_type==='statement'?targets.statements:targets.settlements).map((x:any)=><option key={x.id} value={x.id}>{x.label}</option>)}</select></Field><Field label="مبلغ التخصيص"><Input type="number" max={receipt?.remaining} value={allocation.amount} onChange={e=>setAllocation({...allocation,amount:e.target.value})}/></Field></div><Button type="button" onClick={allocate} disabled={!allocation.target_id}>حفظ التخصيص الجزئي</Button></FormDialog>
    <FormDialog open={!!preview} onOpenChange={value=>!value&&setPreview(undefined)} title={`وصل ${preview?.receipt_number||''}`} className="max-w-3xl">{preview&&<Button type="button" onClick={()=>printReceipt(preview)}><Printer className="w-4 h-4 ml-2"/>طباعة / حفظ PDF</Button>}</FormDialog>
  </div>;
}

const blankExpense={expense_date:today(),payee:'',person_name:'',company_name:'',payment_method:'نقدًا',category:'تشغيل',description:'',amount:'',notes:'',receipt_key:''};
export function ExpensesPage({can,notify,success}:Props){
  const {brand,resolveAssetUrl}=useBrand();
  const [year,setYear]=useState<number|''>(now.getFullYear());const [month,setMonth]=useState<number|''>(now.getMonth()+1);const [from,setFrom]=useState('');const [to,setTo]=useState('');const [rows,setRows]=useState<Expense[]>([]);const [deleted,setDeleted]=useState(false);const [open,setOpen]=useState(false);const [edit,setEdit]=useState<Expense>();const [form,setForm]=useState<any>(blankExpense);
  const [selected,setSelected]=useState<number[]>([]);const [previewForm,setPreviewForm]=useState(false);const [preview,setPreview]=useState<Expense>();
  const [voucher,setVoucher]=useState<{next_pay:number;preview_pay:string}|null>(null);const [nextPayInput,setNextPayInput]=useState('');
  const loadVoucher=()=>financialErpApi.voucherNumbers().then(x=>{setVoucher({next_pay:x.next_pay,preview_pay:x.preview_pay});setNextPayInput(String(x.next_pay))}).catch(notify);
  const load=()=>financialErpApi.expenses({accounting_year:year,accounting_month:month,date_from:from,date_to:to,include_deleted:deleted}).then(x=>setRows(x.items)).catch(notify);useEffect(()=>{void load();void loadVoucher()},[year,month,from,to,deleted]);
  const save=async()=>{if(!form.expense_date){notify(new Error('تاريخ الصرف مطلوب'));return}if(!form.payee?.trim()){notify(new Error('حقل «دُفع إلى» مطلوب'));return}if(form.category.trim().length<2){notify(new Error('تصنيف الصرف مطلوب'));return}if(form.description.trim().length<2){notify(new Error('البيان/الغرض من الصرف مطلوب'));return}if(!(Number(form.amount)>0)){notify(new Error('أدخل مبلغًا أكبر من صفر'));return}try{const d=new Date(`${form.expense_date}T00:00:00`);const payload={...form,amount:Number(form.amount),accounting_year:year||d.getFullYear(),accounting_month:month||d.getMonth()+1,payee:form.payee,person_name:form.person_name||null,company_name:form.company_name||null,payment_method:form.payment_method||null};const savedRes=await financialErpApi.saveExpense(payload,edit?.id);const number=savedRes.payment_number||edit?.payment_number||voucher?.preview_pay||'';setOpen(false);setPreviewForm(false);await load();await loadVoucher();success(edit?`تم تعديل وصل الصرف ${number}`:`تم حفظ وصل الصرف ${number}`);const row:Expense={id:savedRes.id,payment_number:number,expense_date:form.expense_date,accounting_year:payload.accounting_year,accounting_month:payload.accounting_month,payee:form.payee,person_name:form.person_name,company_name:form.company_name,payment_method:form.payment_method,category:form.category,description:form.description,amount:Number(form.amount),notes:form.notes,receipt_key:form.receipt_key,created_by:'',deleted:false,status:'active'};setPreview(row);printPayment(row)}catch(e){notify(e)}};
  const openEdit=(x?:Expense)=>{setEdit(x);setForm(x?{...blankExpense,...x,amount:String(x.amount),payee:x.payee||'',person_name:x.person_name||'',company_name:x.company_name||'',payment_method:x.payment_method||'نقدًا',notes:x.notes||'',receipt_key:x.receipt_key||''}:blankExpense);setPreviewForm(false);setOpen(true);void loadVoucher()};
  const draftPreview=():Expense=>({id:edit?.id||0,payment_number:edit?.payment_number||voucher?.preview_pay||'PAY-…',expense_date:form.expense_date,accounting_year:now.getFullYear(),accounting_month:now.getMonth()+1,payee:form.payee,person_name:form.person_name,company_name:form.company_name,payment_method:form.payment_method,category:form.category,description:form.description,amount:Number(form.amount)||0,notes:form.notes,receipt_key:form.receipt_key,created_by:'',deleted:false,status:'active'});
  const printPayment=(row:Expense)=>{const logo=resolveAssetUrl(brand.report_logo||brand.system_logo);const w=window.open('','_blank','noopener,noreferrer,width=900,height=900');if(!w)return;w.document.write(`<!doctype html><html dir="rtl"><head><meta charset="utf-8"><title>وصل ${escapeHtml(row.payment_number)}</title><style>body{font-family:Tahoma,Arial;padding:28px;color:#172033;background:#f5f7fa}.sheet{border:2px solid #7a2e2e;padding:28px;max-width:760px;margin:auto;background:#fff}.head{display:flex;justify-content:space-between;align-items:center;border-bottom:2px solid #7a2e2e;padding-bottom:16px}.head img{width:90px;height:90px;object-fit:contain}h1{text-align:center;margin:18px 0}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin:24px 0}.field{border-bottom:1px solid #bbb;padding:10px}.amount{font-size:22px;font-weight:bold}.sign{margin-top:55px;display:flex;justify-content:space-between}.foot{margin-top:24px;font-size:12px;color:#555;text-align:center}@media print{button{display:none}body{background:#fff}}</style></head><body><div class="sheet"><div class="head"><img src="${escapeHtml(logo)}"><div><b>${escapeHtml(brand.system_name)}</b><p>${escapeHtml(brand.org_abbr||'MFEC')}</p><small>${escapeHtml(brand.company_name||'')}</small></div><div>رقم الوصل<br><b>${escapeHtml(row.payment_number)}</b></div></div><h1>وصل صرف إلكتروني</h1><div class="grid"><div class="field">دُفع إلى: <b>${escapeHtml(row.payee||'-')}</b></div><div class="field">اسم الشخص: <b>${escapeHtml(row.person_name||'-')}</b></div><div class="field">اسم الشركة: <b>${escapeHtml(row.company_name||'-')}</b></div><div class="field">التاريخ: <b>${escapeHtml(row.expense_date)}</b></div><div class="field amount">المبلغ: ${escapeHtml(money(row.amount))}</div><div class="field">طريقة الدفع: ${escapeHtml(row.payment_method||'-')}</div><div class="field">التصنيف: ${escapeHtml(row.category)}</div><div class="field">أنشأ الوصل: ${escapeHtml(row.created_by||'-')}</div></div><p><b>المبلغ كتابة:</b> ${escapeHtml(amountWords(row.amount))}</p><p><b>البيان/الغرض:</b> ${escapeHtml(row.description)}</p><p><b>ملاحظات:</b> ${escapeHtml(row.notes||'-')}</p><div class="sign"><span>توقيع المستلم: __________</span><span>الختم/الاعتماد: __________</span></div><div class="foot">${escapeHtml(brand.footer_text||'')}<br>${escapeHtml(brand.phone||'')} · ${escapeHtml(brand.email||'')}</div><button onclick="window.print()">طباعة / حفظ PDF</button></div></body></html>`);w.document.close()};
  const saveNextPay=async()=>{const n=Number(nextPayInput);if(!(n>0)){notify(new Error('أدخل رقمًا صحيحًا لتالي وصل الصرف'));return}try{const x=await financialErpApi.setVoucherNumbers({next_pay:n});setVoucher({next_pay:x.next_pay,preview_pay:x.preview_pay});setNextPayInput(String(x.next_pay));success(`تم تعيين الرقم التالي لوصل الصرف: ${x.preview_pay}`)}catch(e){notify(e)}};
  return <div className="space-y-4"><PageTitle title="وصولات الصرف" description="ترقيم تلقائي مستقل PAY-xxxx يُحجز فقط عند الحفظ. الإلغاء لا يعيد الرقم للمخزون."
    actions={<>{can('financial.expenses.create')&&<Button onClick={()=>openEdit()}><Plus className="w-4 h-4 ml-1"/>وصل صرف</Button>}{can('financial.reports.xlsx')&&<Button variant="outline" onClick={()=>financialErpApi.exportExpenses({accounting_year:year,accounting_month:month,date_from:from,date_to:to,selected_ids:selected.length?selected:undefined}).catch(notify)}><FileSpreadsheet className="w-4 h-4 ml-1"/>Excel</Button>}</>}/>
    <Card><CardContent className="p-3 flex flex-wrap gap-3 items-end"><Field label="رقم المصروف التالي"><div className="flex gap-2"><Input className="w-36 font-mono" value={nextPayInput} onChange={e=>setNextPayInput(e.target.value)} placeholder="5"/><Button type="button" variant="outline" onClick={()=>void saveNextPay()}>حفظ</Button></div></Field><div className="text-sm text-slate-600 pb-2">المعاينة: <b className="font-mono">{voucher?.preview_pay||'—'}</b></div></CardContent></Card>
    <Card><CardContent className="p-3 flex gap-2 items-end flex-wrap"><Field label="السنة"><Input className="w-28" type="number" value={year} onChange={e=>setYear(e.target.value?Number(e.target.value):'')}/></Field><Field label="الشهر"><Input className="w-24" type="number" value={month} onChange={e=>setMonth(e.target.value?Number(e.target.value):'')}/></Field><Field label="من تاريخ"><SafeDateInput className="w-40" value={from} onChange={e=>{setFrom(e.target.value);setYear('');setMonth('')}}/></Field><Field label="إلى تاريخ"><SafeDateInput className="w-40" value={to} onChange={e=>{setTo(e.target.value);setYear('');setMonth('')}}/></Field>{can('financial.expenses.restore')&&<label className="flex gap-2 items-center pb-2"><input type="checkbox" checked={deleted} onChange={e=>setDeleted(e.target.checked)}/>إظهار الملغى</label>}</CardContent></Card>
    <Card><CardContent className="p-4"><small>إجمالي صرف الفترة</small><b className="block text-2xl text-red-700">{money(rows.filter(x=>!x.deleted).reduce((a,x)=>a+x.amount,0))}</b></CardContent></Card>
    <CompactTable headers={['','رقم الوصل','التاريخ','المستفيد','التصنيف','المبلغ','الحالة','الإجراءات']}>{rows.map(x=><tr key={x.id} className={`border-t ${x.deleted?'opacity-60':''}`}><td className="p-3 print:hidden"><Checkbox checked={selected.includes(x.id)} onCheckedChange={v=>setSelected(ids=>v?[...ids,x.id]:ids.filter(id=>id!==x.id))}/></td><td className="p-3 font-mono font-bold">{x.payment_number||'-'}</td><td>{x.expense_date}</td><td>{x.payee||'-'}<small className="block">{x.payment_method}</small></td><td>{x.category}<small className="block max-w-56 whitespace-normal">{x.description}</small></td><td>{money(x.amount)}</td><td><StatusBadge value={x.deleted||x.status==='cancelled'?'cancelled':'active'}/></td><td className="print:hidden"><Button type="button" size="icon" variant="ghost" onClick={()=>{setPreview(x);printPayment(x)}}><Printer className="w-4 h-4"/></Button>{x.receipt_key&&<Button size="icon" variant="ghost" onClick={()=>financialErpApi.openDocument(x.receipt_key!)}><Eye className="w-4 h-4"/></Button>}{!x.deleted&&can('financial.expenses.edit')&&<Button size="icon" variant="ghost" onClick={()=>openEdit(x)}><Edit3 className="w-4 h-4"/></Button>}{!x.deleted&&can('financial.expenses.delete')&&<Button size="sm" variant="ghost" onClick={async()=>{if(!confirm(`إلغاء الوصل ${x.payment_number}؟ سيبقى رقمه محجوزًا.`))return;await financialErpApi.deleteExpense(x.id);await load();success(`تم إلغاء ${x.payment_number}`)}}>إلغاء</Button>}{x.deleted&&can('financial.expenses.restore')&&<Button size="sm" variant="outline" onClick={async()=>{await financialErpApi.restoreExpense(x.id);await load()}}><RotateCcw className="w-4 h-4 ml-1"/>إعادة تفعيل</Button>}</td></tr>)}</CompactTable>
    <FormDialog open={open} onOpenChange={setOpen} title={edit?`تعديل وصل ${edit.payment_number}`:'وصل صرف جديد'} className="max-w-3xl"><div className="grid md:grid-cols-2 gap-3"><Field label="رقم الوصل"><Input className="font-mono font-bold" value={edit?.payment_number||voucher?.preview_pay||'PAY-…'} disabled/></Field><Field label="دُفع إلى"><Input value={form.payee} onChange={e=>setForm({...form,payee:e.target.value})}/></Field><Field label="اسم الشخص"><Input value={form.person_name} onChange={e=>setForm({...form,person_name:e.target.value})}/></Field><Field label="اسم الشركة"><Input value={form.company_name} onChange={e=>setForm({...form,company_name:e.target.value})}/></Field><Field label="التاريخ"><SafeDateInput value={form.expense_date} onChange={e=>setForm({...form,expense_date:e.target.value})}/></Field><Field label="المبلغ"><Input type="number" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></Field><Field label="طريقة الدفع"><Input value={form.payment_method} onChange={e=>setForm({...form,payment_method:e.target.value})}/></Field><Field label="التصنيف"><Input value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></Field><Field label="البيان/الغرض من الصرف" className="md:col-span-2"><Input value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></Field><Field label="الملاحظات"><Textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></Field><Field label="المرفقات"><FileButton label={form.receipt_key?'تم رفع المرفق':'رفع مرفق'} onFile={async file=>{const u=await financialErpApi.upload('receipts',file);setForm({...form,receipt_key:u.object_key})}}/></Field></div><div className="flex flex-wrap gap-2 mt-2"><Button type="button" variant="outline" onClick={()=>setPreviewForm(true)}><ReceiptText className="w-4 h-4 ml-2"/>معاينة الوصل</Button><Button type="button" onClick={()=>void save()}><Save className="w-4 h-4 ml-2"/>حفظ</Button></div></FormDialog>
    <FormDialog open={previewForm} onOpenChange={setPreviewForm} title="معاينة قبل الحفظ (لا تستهلك رقمًا)" className="max-w-3xl">{(()=>{const d=draftPreview();return <div className="space-y-3"><div className="border-2 rounded-xl p-6 bg-white"><div className="flex justify-between border-b-2 pb-3"><img className="w-20 h-20 object-contain" src={resolveAssetUrl(brand.report_logo||brand.system_logo)} alt="MFEC"/><div className="text-center"><b>{brand.system_name}</b><h3 className="text-xl font-bold mt-2">وصل صرف إلكتروني</h3></div><div className="font-mono">{d.payment_number}</div></div><div className="grid md:grid-cols-2 gap-3 mt-5"><p>دُفع إلى: <b>{d.payee||'-'}</b></p><p>اسم الشخص: <b>{d.person_name||'-'}</b></p><p>اسم الشركة: <b>{d.company_name||'-'}</b></p><p>التاريخ: <b>{d.expense_date||'-'}</b></p><p>المبلغ: <b>{money(d.amount)}</b></p><p>طريقة الدفع: <b>{d.payment_method||'-'}</b></p><p className="md:col-span-2">الغرض: {d.description||'-'}</p></div></div><Button type="button" onClick={()=>void save()}>تأكيد الحفظ</Button></div>})()}</FormDialog>
    <FormDialog open={!!preview} onOpenChange={value=>!value&&setPreview(undefined)} title={`وصل ${preview?.payment_number||''}`} className="max-w-3xl">{preview&&<Button type="button" onClick={()=>printPayment(preview)}><Printer className="w-4 h-4 ml-2"/>طباعة / حفظ PDF</Button>}</FormDialog>
  </div>;
}

function Field({label,children,className=''}:{label:string;children:React.ReactNode;className?:string}){return <div className={className}><Label className="block mb-1">{label}</Label>{children}</div>}
function Metric({label,value,moneyValue=true}:{label:string;value:number;moneyValue?:boolean}){return <Card><CardContent className="p-4"><small className="text-slate-500">{label}</small><b className="block text-xl">{moneyValue?money(value):Number(value||0).toLocaleString('ar-IQ')}</b></CardContent></Card>}
